// <auto-generated />
using BoardProvider.Data.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BoardProvider.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20240602193425_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BoardProvider.Data.Entities.BoardEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EndX")
                        .HasColumnType("int");

                    b.Property<int>("EndY")
                        .HasColumnType("int");

                    b.Property<int>("StartX")
                        .HasColumnType("int");

                    b.Property<int>("StartY")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Boards");
                });

            modelBuilder.Entity("BoardProvider.Data.Entities.TextEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BoardEntityId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BoardEntityId");

                    b.ToTable("TextEntity");
                });

            modelBuilder.Entity("BoardProvider.Data.Entities.TextEntity", b =>
                {
                    b.HasOne("BoardProvider.Data.Entities.BoardEntity", null)
                        .WithMany("TextBoxes")
                        .HasForeignKey("BoardEntityId");
                });

            modelBuilder.Entity("BoardProvider.Data.Entities.BoardEntity", b =>
                {
                    b.Navigation("TextBoxes");
                });
#pragma warning restore 612, 618
        }
    }
}
